# Generated by Django 4.2.14 on 2024-09-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_avatar_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='care_instructions',
            field=models.TextField(default='Handle with care'),
        ),
    ]
